apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: who-is-who
    tier: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: who-is-who-backend
spec:
  selector:
    matchLabels:
      app: who-is-who
      tier: backend
  template:
    metadata:
      labels:
        app: who-is-who
        tier: backend
    spec:
      containers:
        - name: who-is-who-backend
          image: ghcr.io/scout-ch/who-is-who-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: HITOBITO_URL
              value: "https://db.scout.ch"
            - name: ROOT_GROUP
              value: 2
            - name: SWIFT_PROJECT
              value: "PCP-8YSS2UM"
            - name: SWIFT_AUTH_URL
              value: "https://api.pub1.infomaniak.cloud/identity/v3"
            - name: SWIFT_CONTAINER
              value: "who-is-who"
            - name: SWIFT_REGION
              value: "dc3-a"
            - name: HITOBITO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: HITOBITO_TOKEN
            - name: SWIFT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SWIFT_USERNAME
            - name: SWIFT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SWIFT_PASSWORD
